name: my_jdownloader_api
description: A Dart client for the MyJDownloader API.
version: 0.0.1
repository: https://github.com/adbonnin/dart_my_jdownloader_api

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  convert: ">=3.0.0 <4.0.0"
  crypto: ">=3.0.0 <4.0.0"
  encrypt: ">=5.0.0 <6.0.0"
  http: ">=0.13.0 <2.0.0"

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
